'use client';

import { useEffect, useState } from 'react';
import { PlainHomeSvg } from '@/components/Animation/PlainHomeSvg';
import { siteConfig } from '@/config/site';

interface Particle {
    id: number;
    x: number;       // left position (%)
    size: number;    // diameter (px)
    duration: number; // animation duration (s)
    delay: number;   // negative delay to stagger (s)
    opacity: number; // max opacity
}

function generateParticles(count: number): Particle[] {
    return Array.from({ length: count }, (_, i) => ({
        id: i,
        x: 8 + Math.random() * 84,
        size: 4 + Math.random() * 14,
        duration: 5 + Math.random() * 7,
        delay: Math.random() * 12,
        opacity: 0.06 + Math.random() * 0.22,
    }));
}

export function HeroSection() {
    const [particles, setParticles] = useState<Particle[]>([]);
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setParticles(generateParticles(34));
        const timer = setTimeout(() => setMounted(true), 100);
        return () => clearTimeout(timer);
    }, []);

    return (
        <section className="hero-section">
            {/* Animated gradient background */}
            <div className="hero-bg" aria-hidden="true" />

            {/* Steam/coffee particles — positions & timings generated by TypeScript */}
            <div className="hero-particles" aria-hidden="true">
                {particles.map((p) => (
                    <span
                        key={p.id}
                        className="hero-particle"
                        style={{
                            left: `${p.x}%`,
                            width: `${p.size}px`,
                            height: `${p.size}px`,
                            animationDuration: `${p.duration}s`,
                            animationDelay: `-${p.delay}s`,
                            '--particle-opacity': p.opacity,
                        } as React.CSSProperties}
                    />
                ))}
            </div>

            {/* Central content */}
            <div
                className="hero-content"
                style={{
                    opacity: mounted ? 1 : 0,
                    transform: mounted ? 'none' : 'translateY(14px)',
                }}
            >
                <div className="hero-logo">
                    <PlainHomeSvg />
                </div>
                <p className="hero-tagline">{siteConfig.tagline}</p>
            </div>

            {/* Bottom gradient fade to page background */}
            <div className="hero-fade" aria-hidden="true" />
        </section>
    );
}
